version: 2
jobs:
  run_test:
    docker:
      - image: 'circleci/node:12.13.1'
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./test.js
  masterdeploy:
    docker:
      - image: 'circleci/node:12.13.1'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: Write Files
          command: |
            echo $PRODUCTION_CLASPRC > ~/.clasprc.json
            echo $PRODUCTION_CREDENTIALS > .clasprc.json
            echo $PRODUCTION_CLASP > .clasp.json
            echo $PRODUCTION_CREDS > creds.json
      - run:
          name: Deploy and Publish
          command: |
            npx clasp push --force
            yarn production-deploy
workflows:
  version: 2
  build:
    jobs:
      - run_test
      - masterdeploy:
          requires:
            - run_test
          filters:
            branches:
              only: master